{ config, lib, pkgs, ... }:

{
  config = lib.mkIf config.deploy.profile.gui {
    home.packages = with pkgs; [
      _1password
      bitwarden
      arc.pkgs.rbw-bitw
      mpv
      element-desktop
      mumble
      obs-studio
      niv
      feh
      duc
      audacity
      avidemux
      vlc
      ffmpeg-full
      thunderbird
      unstable.syncplay
      unstable.youtube-dl
      unstable.mkchromecast
      unstable.google-chrome
      v4l-utils
      transmission-gtk
      lm_sensors
      p7zip
      baresip
      psmisc
      discord
      tdesktop
      yubikey-manager
      pinentry.gtk2
      dino
      libnotify
      nextcloud-client
      vegur
      nitrogen
      terminator
      pavucontrol
      gparted
      scrot
      gimp-with-plugins
      vscode
      cryptsetup
      vifm
      neofetch
      htop
    ];
  };
}
