keys:
- &kat CD8CE78CB0B3BDD4 # https://inskip.me/pubkey.asc
- &mew 65BD3044771CB6FB
- &yukari age1n4kdchmkk3rfkaknxhveqr2ftprdpgwckutt23y6u8639lazzuks77tgav
- &yukari_kat age1cnu37d5fqyahh9vvc4hj6z6k8ur9ksuefln7sr6g3emmn927eutqxdawuh
- &koishi age1a0m73qr8hhuz8xemv4vymf4wmpghm2hst8wgrn3pn65ext5mf4ksk0vsdm
- &koishi_kat age18hpxz0ghvswv9k30cle73prvnzrsuczqh87jjdk9fl50j3ddndmq9xae0n
- &mei age1xgy03g3vjydsxcl0qpdgm8rahjcjq95ucxfwlgr22zwjx3p7jf2s9jk6u5
- &mai age1fv5dafs4n3r5n83qm2hfz7xmnflsz0xf9r3saralrptpgf8mvuxq4t8k3u
- &daiyousei age120530yclr75k6nrzp6k5jjftj8j4q9v3533guupzk4ct86mjxszqg9e5t5
- &goliath age1c4atxfp05u7zm875s6q8p82ve96rqqpq9smktxlur8pk2yc3qvgql46dp9
- &goliath_kat age1rjldv3fn3q686647exmcukthr32gmp6s3axs0lhyenvru9ajp9rs24ukvz
creation_rules:
- path_regex: tf/terraform.tfvars.sops$
  shamir_threshold: 1
  key_groups:
  - pgp:
    - *kat
- path_regex: nixos/profiles/[^/]+/.*\.yaml$
  shamir_threshold: 1
  key_groups:
  - pgp:
    - *kat
    age: &age_common
    - *yukari
    - *yukari_kat
    - *koishi
    - *koishi_kat
    - *mei
    - *mai
    - *daiyousei
    - *goliath
    - *goliath_kat
- path_regex: ci/.*\.yaml
  shamir_threshold: 1
  key_groups:
  - pgp:
    - *kat
    age: *age_common
- path_regex: home/[^/]+/.*\.yaml
  shamir_threshold: 1
  key_groups:
  - pgp:
    - *kat
    age: *age_common
- path_regex: nixos/[^/]+/.*\.yaml
  shamir_threshold: 1
  key_groups:
  - pgp:
    - *kat
    age: *age_common
- path_regex: nixos/servers/[^/]+/.*\.yaml
  shamir_threshold: 1
  key_groups:
  - pgp:
    - *kat
    age: *age_common
- path_regex: systems/.*\.yaml$
  shamir_threshold: 1
  key_groups:
  - pgp:
    - *kat
    age: *age_common
- path_regex: cluster/cluster.tfvars.sops$
  shamir_threshold: 1
  key_groups:
  - pgp:
    - *kat
- path_regex: tf/tf.tfvars.sops$
  shamir_threshold: 1
  key_groups:
  - pgp:
    - *kat
