env:
  CI_ALLOW_ROOT: '1'
  CI_CONFIG: ./ci/nodes.nix
  CI_PLATFORM: gh-actions
jobs:
  ci-check:
    name: nodes check
    runs-on: ubuntu-latest
    steps:
    - id: checkout
      name: git clone
      uses: actions/checkout@v1
      with:
        submodules: false
    - id: nix-install
      name: nix install
      uses: arcnmx/ci/actions/nix/install@nix2.4
    - id: ci-action-build
      name: nix build ci.gh-actions.configFile
      uses: arcnmx/ci/actions/nix/build@nix2.4
      with:
        attrs: ci.gh-actions.configFile
        out-link: .ci/workflow.yml
    - id: ci-action-compare
      name: gh-actions compare
      uses: arcnmx/ci/actions/nix/run@nix2.4
      with:
        args: -u .github/workflows/nodes.yml .ci/workflow.yml
        attrs: nixpkgs.diffutils
        command: diff
  daiyousei:
    name: nodes-daiyousei
    runs-on: ubuntu-latest
    steps:
    - id: checkout
      name: git clone
      uses: actions/checkout@v1
      with:
        submodules: false
    - id: nix-install
      name: nix install
      uses: arcnmx/ci/actions/nix/install@nix2.4
    - id: ci-setup
      name: nix setup
      uses: arcnmx/ci/actions/nix/run@nix2.4
      with:
        attrs: ci.job.daiyousei.run.bootstrap
        quiet: false
    - id: architectures
      name: prepare for emulated builds
      run: 'sudo $(which archbinfmt)

        '
    - id: ci-dirty
      name: nix test dirty
      uses: arcnmx/ci/actions/nix/run@nix2.4
      with:
        attrs: ci.job.daiyousei.run.test
        command: ci-build-dirty
        quiet: false
        stdout: ${{ runner.temp }}/ci.build.dirty
    - id: ci-test
      name: nix test build
      uses: arcnmx/ci/actions/nix/run@nix2.4
      with:
        attrs: ci.job.daiyousei.run.test
        command: ci-build-realise
        ignore-exit-code: true
        quiet: false
        stdin: ${{ runner.temp }}/ci.build.dirty
    - env:
        CI_EXIT_CODE: ${{ steps.ci-test.outputs.exit-code }}
      id: ci-summary
      name: nix test results
      uses: arcnmx/ci/actions/nix/run@nix2.4
      with:
        attrs: ci.job.daiyousei.run.test
        command: ci-build-summarise
        quiet: false
        stdin: ${{ runner.temp }}/ci.build.dirty
        stdout: ${{ runner.temp }}/ci.build.cache
    - env:
        CACHIX_SIGNING_KEY: ${{ secrets.CACHIX_SIGNING_KEY }}
      id: ci-cache
      if: always()
      name: nix test cache
      uses: arcnmx/ci/actions/nix/run@nix2.4
      with:
        attrs: ci.job.daiyousei.run.test
        command: ci-build-cache
        quiet: false
        stdin: ${{ runner.temp }}/ci.build.cache
  koishi:
    name: nodes-koishi
    runs-on: ubuntu-latest
    steps:
    - id: checkout
      name: git clone
      uses: actions/checkout@v1
      with:
        submodules: false
    - id: nix-install
      name: nix install
      uses: arcnmx/ci/actions/nix/install@nix2.4
    - id: ci-setup
      name: nix setup
      uses: arcnmx/ci/actions/nix/run@nix2.4
      with:
        attrs: ci.job.koishi.run.bootstrap
        quiet: false
    - id: architectures
      name: prepare for emulated builds
      run: 'sudo $(which archbinfmt)

        '
    - id: ci-dirty
      name: nix test dirty
      uses: arcnmx/ci/actions/nix/run@nix2.4
      with:
        attrs: ci.job.koishi.run.test
        command: ci-build-dirty
        quiet: false
        stdout: ${{ runner.temp }}/ci.build.dirty
    - id: ci-test
      name: nix test build
      uses: arcnmx/ci/actions/nix/run@nix2.4
      with:
        attrs: ci.job.koishi.run.test
        command: ci-build-realise
        ignore-exit-code: true
        quiet: false
        stdin: ${{ runner.temp }}/ci.build.dirty
    - env:
        CI_EXIT_CODE: ${{ steps.ci-test.outputs.exit-code }}
      id: ci-summary
      name: nix test results
      uses: arcnmx/ci/actions/nix/run@nix2.4
      with:
        attrs: ci.job.koishi.run.test
        command: ci-build-summarise
        quiet: false
        stdin: ${{ runner.temp }}/ci.build.dirty
        stdout: ${{ runner.temp }}/ci.build.cache
    - env:
        CACHIX_SIGNING_KEY: ${{ secrets.CACHIX_SIGNING_KEY }}
      id: ci-cache
      if: always()
      name: nix test cache
      uses: arcnmx/ci/actions/nix/run@nix2.4
      with:
        attrs: ci.job.koishi.run.test
        command: ci-build-cache
        quiet: false
        stdin: ${{ runner.temp }}/ci.build.cache
  marisa:
    name: nodes-marisa
    runs-on: ubuntu-latest
    steps:
    - id: checkout
      name: git clone
      uses: actions/checkout@v1
      with:
        submodules: false
    - id: nix-install
      name: nix install
      uses: arcnmx/ci/actions/nix/install@nix2.4
    - id: ci-setup
      name: nix setup
      uses: arcnmx/ci/actions/nix/run@nix2.4
      with:
        attrs: ci.job.marisa.run.bootstrap
        quiet: false
    - id: architectures
      name: prepare for emulated builds
      run: 'sudo $(which archbinfmt)

        '
    - id: ci-dirty
      name: nix test dirty
      uses: arcnmx/ci/actions/nix/run@nix2.4
      with:
        attrs: ci.job.marisa.run.test
        command: ci-build-dirty
        quiet: false
        stdout: ${{ runner.temp }}/ci.build.dirty
    - id: ci-test
      name: nix test build
      uses: arcnmx/ci/actions/nix/run@nix2.4
      with:
        attrs: ci.job.marisa.run.test
        command: ci-build-realise
        ignore-exit-code: true
        quiet: false
        stdin: ${{ runner.temp }}/ci.build.dirty
    - env:
        CI_EXIT_CODE: ${{ steps.ci-test.outputs.exit-code }}
      id: ci-summary
      name: nix test results
      uses: arcnmx/ci/actions/nix/run@nix2.4
      with:
        attrs: ci.job.marisa.run.test
        command: ci-build-summarise
        quiet: false
        stdin: ${{ runner.temp }}/ci.build.dirty
        stdout: ${{ runner.temp }}/ci.build.cache
    - env:
        CACHIX_SIGNING_KEY: ${{ secrets.CACHIX_SIGNING_KEY }}
      id: ci-cache
      if: always()
      name: nix test cache
      uses: arcnmx/ci/actions/nix/run@nix2.4
      with:
        attrs: ci.job.marisa.run.test
        command: ci-build-cache
        quiet: false
        stdin: ${{ runner.temp }}/ci.build.cache
  renko:
    name: nodes-renko
    runs-on: ubuntu-latest
    steps:
    - id: checkout
      name: git clone
      uses: actions/checkout@v1
      with:
        submodules: false
    - id: nix-install
      name: nix install
      uses: arcnmx/ci/actions/nix/install@nix2.4
    - id: ci-setup
      name: nix setup
      uses: arcnmx/ci/actions/nix/run@nix2.4
      with:
        attrs: ci.job.renko.run.bootstrap
        quiet: false
    - id: architectures
      name: prepare for emulated builds
      run: 'sudo $(which archbinfmt)

        '
    - id: ci-dirty
      name: nix test dirty
      uses: arcnmx/ci/actions/nix/run@nix2.4
      with:
        attrs: ci.job.renko.run.test
        command: ci-build-dirty
        quiet: false
        stdout: ${{ runner.temp }}/ci.build.dirty
    - id: ci-test
      name: nix test build
      uses: arcnmx/ci/actions/nix/run@nix2.4
      with:
        attrs: ci.job.renko.run.test
        command: ci-build-realise
        ignore-exit-code: true
        quiet: false
        stdin: ${{ runner.temp }}/ci.build.dirty
    - env:
        CI_EXIT_CODE: ${{ steps.ci-test.outputs.exit-code }}
      id: ci-summary
      name: nix test results
      uses: arcnmx/ci/actions/nix/run@nix2.4
      with:
        attrs: ci.job.renko.run.test
        command: ci-build-summarise
        quiet: false
        stdin: ${{ runner.temp }}/ci.build.dirty
        stdout: ${{ runner.temp }}/ci.build.cache
    - env:
        CACHIX_SIGNING_KEY: ${{ secrets.CACHIX_SIGNING_KEY }}
      id: ci-cache
      if: always()
      name: nix test cache
      uses: arcnmx/ci/actions/nix/run@nix2.4
      with:
        attrs: ci.job.renko.run.test
        command: ci-build-cache
        quiet: false
        stdin: ${{ runner.temp }}/ci.build.cache
  rinnosuke:
    name: nodes-rinnosuke
    runs-on: ubuntu-latest
    steps:
    - id: checkout
      name: git clone
      uses: actions/checkout@v1
      with:
        submodules: false
    - id: nix-install
      name: nix install
      uses: arcnmx/ci/actions/nix/install@nix2.4
    - id: ci-setup
      name: nix setup
      uses: arcnmx/ci/actions/nix/run@nix2.4
      with:
        attrs: ci.job.rinnosuke.run.bootstrap
        quiet: false
    - id: architectures
      name: prepare for emulated builds
      run: 'sudo $(which archbinfmt)

        '
    - id: ci-dirty
      name: nix test dirty
      uses: arcnmx/ci/actions/nix/run@nix2.4
      with:
        attrs: ci.job.rinnosuke.run.test
        command: ci-build-dirty
        quiet: false
        stdout: ${{ runner.temp }}/ci.build.dirty
    - id: ci-test
      name: nix test build
      uses: arcnmx/ci/actions/nix/run@nix2.4
      with:
        attrs: ci.job.rinnosuke.run.test
        command: ci-build-realise
        ignore-exit-code: true
        quiet: false
        stdin: ${{ runner.temp }}/ci.build.dirty
    - env:
        CI_EXIT_CODE: ${{ steps.ci-test.outputs.exit-code }}
      id: ci-summary
      name: nix test results
      uses: arcnmx/ci/actions/nix/run@nix2.4
      with:
        attrs: ci.job.rinnosuke.run.test
        command: ci-build-summarise
        quiet: false
        stdin: ${{ runner.temp }}/ci.build.dirty
        stdout: ${{ runner.temp }}/ci.build.cache
    - env:
        CACHIX_SIGNING_KEY: ${{ secrets.CACHIX_SIGNING_KEY }}
      id: ci-cache
      if: always()
      name: nix test cache
      uses: arcnmx/ci/actions/nix/run@nix2.4
      with:
        attrs: ci.job.rinnosuke.run.test
        command: ci-build-cache
        quiet: false
        stdin: ${{ runner.temp }}/ci.build.cache
  tewi:
    name: nodes-tewi
    runs-on: ubuntu-latest
    steps:
    - id: checkout
      name: git clone
      uses: actions/checkout@v1
      with:
        submodules: false
    - id: nix-install
      name: nix install
      uses: arcnmx/ci/actions/nix/install@nix2.4
    - id: ci-setup
      name: nix setup
      uses: arcnmx/ci/actions/nix/run@nix2.4
      with:
        attrs: ci.job.tewi.run.bootstrap
        quiet: false
    - id: architectures
      name: prepare for emulated builds
      run: 'sudo $(which archbinfmt)

        '
    - id: ci-dirty
      name: nix test dirty
      uses: arcnmx/ci/actions/nix/run@nix2.4
      with:
        attrs: ci.job.tewi.run.test
        command: ci-build-dirty
        quiet: false
        stdout: ${{ runner.temp }}/ci.build.dirty
    - id: ci-test
      name: nix test build
      uses: arcnmx/ci/actions/nix/run@nix2.4
      with:
        attrs: ci.job.tewi.run.test
        command: ci-build-realise
        ignore-exit-code: true
        quiet: false
        stdin: ${{ runner.temp }}/ci.build.dirty
    - env:
        CI_EXIT_CODE: ${{ steps.ci-test.outputs.exit-code }}
      id: ci-summary
      name: nix test results
      uses: arcnmx/ci/actions/nix/run@nix2.4
      with:
        attrs: ci.job.tewi.run.test
        command: ci-build-summarise
        quiet: false
        stdin: ${{ runner.temp }}/ci.build.dirty
        stdout: ${{ runner.temp }}/ci.build.cache
    - env:
        CACHIX_SIGNING_KEY: ${{ secrets.CACHIX_SIGNING_KEY }}
      id: ci-cache
      if: always()
      name: nix test cache
      uses: arcnmx/ci/actions/nix/run@nix2.4
      with:
        attrs: ci.job.tewi.run.test
        command: ci-build-cache
        quiet: false
        stdin: ${{ runner.temp }}/ci.build.cache
  yukari:
    name: nodes-yukari
    runs-on: ubuntu-latest
    steps:
    - id: checkout
      name: git clone
      uses: actions/checkout@v1
      with:
        submodules: false
    - id: nix-install
      name: nix install
      uses: arcnmx/ci/actions/nix/install@nix2.4
    - id: ci-setup
      name: nix setup
      uses: arcnmx/ci/actions/nix/run@nix2.4
      with:
        attrs: ci.job.yukari.run.bootstrap
        quiet: false
    - id: architectures
      name: prepare for emulated builds
      run: 'sudo $(which archbinfmt)

        '
    - id: ci-dirty
      name: nix test dirty
      uses: arcnmx/ci/actions/nix/run@nix2.4
      with:
        attrs: ci.job.yukari.run.test
        command: ci-build-dirty
        quiet: false
        stdout: ${{ runner.temp }}/ci.build.dirty
    - id: ci-test
      name: nix test build
      uses: arcnmx/ci/actions/nix/run@nix2.4
      with:
        attrs: ci.job.yukari.run.test
        command: ci-build-realise
        ignore-exit-code: true
        quiet: false
        stdin: ${{ runner.temp }}/ci.build.dirty
    - env:
        CI_EXIT_CODE: ${{ steps.ci-test.outputs.exit-code }}
      id: ci-summary
      name: nix test results
      uses: arcnmx/ci/actions/nix/run@nix2.4
      with:
        attrs: ci.job.yukari.run.test
        command: ci-build-summarise
        quiet: false
        stdin: ${{ runner.temp }}/ci.build.dirty
        stdout: ${{ runner.temp }}/ci.build.cache
    - env:
        CACHIX_SIGNING_KEY: ${{ secrets.CACHIX_SIGNING_KEY }}
      id: ci-cache
      if: always()
      name: nix test cache
      uses: arcnmx/ci/actions/nix/run@nix2.4
      with:
        attrs: ci.job.yukari.run.test
        command: ci-build-cache
        quiet: false
        stdin: ${{ runner.temp }}/ci.build.cache
name: nodes
'on':
- push
- pull_request
