# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [ "ata_generic" "ehci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "zroot/safe/root";
    fsType = "zfs";
  };

  fileSystems."/nix" =
    { device = "zroot/local/nix";
    fsType = "zfs";
  };

  fileSystems."/home" =
    { device = "zroot/safe/home";
    fsType = "zfs";
  };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/44CC-7137";
    fsType = "vfat";
  };

  fileSystems."/boot-fallback" =
    { device = "/dev/disk/by-uuid/4520-4E5F";
    fsType = "vfat";
  };

  swapDevices = 
  [ { device = "/dev/disk/by-uuid/682df001-bad8-4d94-a86b-9068ce5eee4c"; }
  { device = "/dev/disk/by-uuid/1ee2d322-235c-41de-b272-7ceded4e2624"; }
  ];
  }
